version: '3.8'

services:
  mysql-identity:
    container_name: mysql-dbcontrol
    image: mysql:8.0.19
    environment:
      - MYSQL_DATABASE=dbcontrol
      - MYSQL_USER=db_control_login
      - MYSQL_PASSWORD=very_secret
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - db_control-volumes:/var/lib/mysql
      - C:\ProgramData\MySQL\MySQL Server 8.0\Uploads:/allowed_dir
    ports:
      - '3307:3306'
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=/allowed_dir

volumes:
  db_control-volumes:
